name: Continuous integration 

on: 
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn test
